---

- name: Install Docker
  become: true
  dnf:
    name: docker

- name: Start service
  become: true
  systemd:
    name: docker
    state: started
    enabled: true

- name: Login to ECR
  become: true
  shell: |
    aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin "113304117666.dkr.ecr.eu-north-1.amazonaws.com"
