---

- name: Configure AWS credentials
  shell: |
    aws configure set aws_access_key_id {{ACCESS_KEY}} &&
    aws configure set aws_secret_access_key {{SECRET_KEY}} &&
    aws configure set default.region eu-north-1

- name: Check if image exists in ECR
  shell: |
    [[ \"{{appversion}}\" =  $(aws ecr describe-images --repository-name={{repo}} --regio=eu-north-1 --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]') ]]
  any_errors_fatal: true

- name: Check if image exists locally
  become: true
  shell: |
    docker images --filter=reference='*{{repo}}' --format '"\{\{.Tag\}\}"'
    [ $(docker images "*/{{repo}}" --format '"\{\{.Tag\}\}"') =  $(aws ecr describe-images --repository-name={{repo}} --region=eu-north-1 --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]') ] && echo true || echo false
  register: existsLocal

- name: Cleanup
  become: true
  shell: |
    docker stop $(docker ps -q)
    docker rm $(docker ps -aq)
    docker rmi $(docker images -q)
  when: existsLocal.stdout != true
  ignore_errors: true

- name: Get image from ECR
  become: true
  shell: |
    docker pull "{{url}}/{{repo}}:{{appversion}}"
  when: existsLocal.stdout != true

- name: Run container
  become: true
  shell: |
    docker run -itd -v ~/.aws:/root/.aws -p 80:8080 --name=petclinic {{url}}/{{repo}}:{{appversion}}