name: IaC Deploy PR

on:
  pull_request:
    paths:
      - '**/infrastructure/**'
    paths_ignore:
      - '**/infrastructure/ansible/**'
    branches:
      - main
    types:
      - opened
      - closed
      - edited

jobs:
  terraform:
    uses: ./.github/workflows/iac.yml
    secrets: inherit